name: Pruebas autom√°ticas del grupo

on:
  # Define los eventos que disparan el flujo de trabajo
  push:
    branches:
      - main
      - '*' # Ejecuta en 'main' y cualquier otra rama

jobs: # <- A este nivel
  test:
    runs-on: ubuntu-latest # <- A este nivel (alineado con 'steps')
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # <- Sin espacios antes del ':'

      - name: instalar dependencias
        run: |
          pip install pytest

      - name: Ejecutar pruebas
        run: |
          pytest -v

